easy_admin:
    # Définit le nom de l'interface d'administration
    site_name: 'Dashboard Mon agence'
    # Définit l'affichage de l'utilisateur
    user:
      display_name: true
      display_avatar: true
      name_property_path: 'username'
    design:
      # Lignes utiles pour CKEditor
      form_theme:
        - "@EasyAdmin/form/bootstrap_4.html.twig"
        - "@FOSCKEditor/Form/ckeditor_widget.html.twig"
      # Lignes pour définir notre menu
      menu:
        - { label: 'Menu' }
        - label: 'Les biens'
          children:
            - { entity: 'Propriete', label: 'Liste des biens', icon: 'th-list' }
            - { entity: 'Propriete', label: 'Nouveau bien', icon: 'plus', params: {action: 'new' }, permission: 'ROLE_ADMIN'}
        - label: 'Les critères'
          children:
            - { entity: 'Critere', label: 'Liste des critères', icon: 'tag' }
            - { entity: 'Critere', label: 'Nouveau critères', icon: 'plus', params: {action: 'new' }}
        - { label: "Paramètres"}
        - { entity: 'User', icon: 'user', permission: 'ROLE_ADMIN' }
    formats:
      # Ici on définit le format des dates
      datetime: 'd/m/Y à H:i'
    entities:
      # List the entity class name you want to manage
     Propriete:
        class: App\Entity\Propriete
        list:
          collapse_actions: true
          actions: ['show', 'edit', 'delete']
          batch_actions: ['delete']
          title: 'La liste des biens'
          filters: ['vendu']
          fields: ['titre', 'vendu', { property: 'createdAt', label: 'Date de création' }, { property: 'user.email', label: 'Utilisateur', permission: 'ROLE_ADMIN' }, { property: 'image_name', type: 'image', base_path: '%app.path.product_images%' }]
          sort: ['createdAt', 'desc']

        show:
          fields:
            - titre
            - { property: 'image_name', label: 'Image', type: 'image', base_path: '%app.path.product_images%', css_class: 'col-lg-12' }
            - { property: 'attachments', template: 'images.html.twig', css_class: 'col-lg-6'}
            - { property: 'description', type: 'raw' }
            - criteres
            - vendu
        edit:
          help: 'Bonjour'
        new:
          item_permission: 'ROLE_ADMIN'

        form:
          fields:
            - { type: 'group', icon: 'pencil', label: 'Caractéristiques du bien', css_class: 'col-lg-12' }
            - titre
            - surface
            - pieces
            - chambres
            - chauffage
            - etages
            - { property: 'description', type: 'fos_ckeditor', type_options: { config_name: 'main_config' }}
            - { type: 'group', icon: 'clip', label: 'Image', css_class: 'col-lg-12' }
            - { property: 'imageFile', type: 'vich_image', label: 'Image'}
            - { property: 'attachments', type: 'collection', type_options: { entry_type: 'App\Form\AttachmentType', by_reference: false }}
            #- created_at
            - { property: 'criteres', type: 'entity', label: 'Critères', type_options: { class: 'App\Entity\Critere', multiple: true,by_reference: false, attr: { data-widget: 'select2' }}}
            - { type: 'group', icon: 'pencil', label: 'Localisation du bien' }
            - adresse
            - ville
            - code_postal
            - prix

     Critere:
        class: App\Entity\Critere
        list:
          collapse_actions: true
          actions: ['edit', 'delete']
          batch_actions: ['delete']
          title: 'La liste des critères'
          fields:
            - name
        form:
          fields:
            - { type: 'group', icon: 'pencil', label: 'Édition du critère' }
            - name
          sort: ['name', 'asc']
     User:
        class: App\Entity\User
        list:
          item_permission: 'ROLE_ADMIN'
          collapse_actions: true
          actions: ['edit', 'delete']
          batch_actions: ['delete']
          title: 'La liste des utilisateurs'
          fields:
            - username
            - email
            - { property: 'roles', label: 'Rôles', type: json_array }
        #form:
          #fields:
            #- { type: 'group', icon: 'pencil', label: 'Édition utilisateur' }
            #- username
            #- email
            #- { type: 'group', icon: 'th-list', label: 'Attribution rôles' }
            #- { property: 'roles', label: 'Rôles', type: choice, type_options: { expanded: true, multiple: true, choices: {'Utilisateur':'ROLE_USER', 'Administrateur':'ROLE_ADMIN' }}}






