<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container27WicED\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container27WicED/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container27WicED.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container27WicED\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container27WicED\App_KernelDevDebugContainer([
    'container.build_hash' => '27WicED',
    'container.build_id' => '0dfea007',
    'container.build_time' => 1587992390,
], __DIR__.\DIRECTORY_SEPARATOR.'Container27WicED');
